// GENERATED BY scripts/generate-blog-registry.mjs

export type BlogPost = {
  titulo: string;
  slug: string;
  imagem: string;
  descricao: string;
  data: string;
  tags: string[];
  content: string;
};

export const blogRegistry: BlogPost[] = [
  {
    "imagem": "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80",
    "titulo": "Como Conseguir o Primeiro Emprego em TI sem Experiência",
    "slug": "como-conseguir-primeiro-emprego-ti",
    "descricao": "O que empresas realmente procuram em um dev júnior — e como se preparar sem experiência.",
    "data": "2026-06-06",
    "tags": [
      "carreira",
      "emprego"
    ],
    "content": "\nSim, é possível conseguir o primeiro emprego em TI sem experiência, mas você precisa focar em projetos práticos e networking, não em currículo tradicional.\n\n## Monte um portfólio com projetos reais\n\nEmpresas contratam quem resolve problemas. Crie 2-3 projetos no GitHub que mostrem suas habilidades: um site, uma automação simples ou um script. Documente tudo no README. Isso vale mais que qualquer certificado.\n\n## Use o LinkedIn como ferramenta de caça\n\nNão espere recrutadores te acharem. Conecte-se com profissionais de TI, comente posts relevantes e publique seu portfólio. Participe de eventos online e hackathons — muitos recrutadores estão lá. Estágios e trainee são portas de entrada, mesmo que paguem menos no início.\n\n## Prepare-se para entrevistas técnicas\n\nEstude algoritmos básicos (arrays, loops, strings) e pratique no LeetCode ou HackerRank. Saiba explicar seus projetos em 2 minutos. Mostre entusiasmo em aprender — isso compensa a falta de experiência.\n\nConclusão: seu primeiro emprego em TI depende mais de ação do que de credenciais. Comece hoje com um projeto pequeno e publique no GitHub. Para dar o próximo passo, veja o guia completo no [MeuPasso](https://meupasso.com.br/primeiro-emprego-ti).\n"
  },
  {
    "imagem": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80",
    "titulo": "Erros Mais Comuns de Quem Está Aprendendo Python",
    "slug": "erros-mais-comuns-python-iniciantes",
    "descricao": "Os erros de mentalidade que travam quem está aprendendo Python — e como evitá-los.",
    "data": "2026-06-06",
    "tags": [
      "python",
      "iniciantes",
      "erros"
    ],
    "content": "\nOs principais erros de mentalidade que travam quem aprende Python são: achar que precisa decorar tudo, esperar o momento perfeito para começar projetos, e comparar seu aprendizado com o de outras pessoas. Vamos direto ao ponto de como evitar cada um.\n\n## Achar que precisa decorar tudo\n\nMuita gente trava porque tenta memorizar cada função, sintaxe ou biblioteca. Isso é perda de tempo. Programadores experientes consultam documentação o tempo todo — Google e ChatGPT são seus melhores amigos. **O que importa é entender conceitos**, não decorar comandos. Quando surgir uma dúvida, pesquise. Com o tempo, o que é frequente fica automático.\n\n## Esperar o momento perfeito para projetos\n\nOutro erro clássico: “só vou fazer um projeto quando terminar todos os cursos”. Isso nunca acontece. Você aprende Python de verdade quando começa a construir algo, mesmo que seja uma calculadora ou um jogo da velha. **Err cedo e com frequência acelera o aprendizado**. Comece hoje com algo simples, mesmo que pareça feio ou incompleto. Refatore depois.\n\n## Comparar seu aprendizado com o de outras pessoas\n\nVer alguém que aprendeu Python em 3 meses e já faz IA pode te desanimar. Mas cada pessoa tem um contexto, tempo e objetivo diferente. **Seu único parâmetro deve ser seu progresso de ontem**. Foque em dar um passo de cada vez: entender uma função nova, resolver um bug, ou completar um pequeno desafio.\n\nLembre-se: aprender Python é uma maratona, não um sprint. Evite esses erros, pratique todo dia um pouco, e em breve você estará codando com confiança. Para começar hoje mesmo com projetos práticos, confira nosso [guia de primeiros passos no MeuPasso](https://meupasso.com.br/python-primeiros-passos).\n"
  },
  {
    "imagem": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80",
    "titulo": "Melhores Formas de Praticar Programação (Segundo Quem Já Ensinou Centenas de Iniciantes)",
    "slug": "melhores-formas-praticar-programacao",
    "descricao": "Praticar é mais importante que assistir aulas. Veja como fazer isso de forma eficiente.",
    "data": "2026-06-06",
    "tags": [
      "prática",
      "iniciantes"
    ],
    "content": "\nA melhor forma de praticar programação é **codar todo dia, mesmo que por 15 minutos**, e fazer projetos pequenos e reais para aplicar o que aprendeu. Pare de só assistir tutoriais e coloque a mão no código.\n\n## Crie mini-projetos desde o início\n\nNão precisa de um app complexo. Comece com coisas como:\n- Um conversor de temperatura\n- Uma calculadora de IMC\n- Um jogo de adivinhação de números\n- Um gerador de senhas aleatórias\n\nCada projeto te força a pesquisar, errar e resolver problemas – que é onde você realmente aprende.\n\n## Resolva desafios de lógica\n\nUse plataformas como CodeSignal, HackerRank ou o próprio MeuPasso para treinar lógica de programação. São exercícios rápidos que testam seu raciocínio sem precisar de um projeto grande. Faça um por dia.\n\n## Participe da comunidade e peça revisões\n\nPoste seu código em fóruns, grupos de Discord ou no GitHub. Peça feedback honesto. Ver como outros programadores resolvem o mesmo problema vai abrir sua mente para novas abordagens.\n\n## Conclusão\n\nPraticar programação é como aprender um esporte: teoria não substitui a prática diária. Comece hoje com um mini-projeto, resolva um desafio de lógica e compartilhe seu código. O segredo é a consistência, não a perfeição.\n\n👉 Confira [nossos exercícios práticos para iniciantes no MeuPasso](https://meupasso.com/exercicios)\n"
  },
  {
    "imagem": "https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&q=80",
    "titulo": "Python ou Java para Iniciantes: Qual Escolher em 2026?",
    "slug": "python-ou-java-para-iniciantes",
    "descricao": "Qual linguagem escolher para começar? A resposta honesta para quem está começando do zero.",
    "data": "2026-06-06",
    "tags": [
      "python",
      "java",
      "iniciantes"
    ],
    "content": "\nPython, sem dúvida. Para quem está começando, Python é mais fácil de aprender, tem uma sintaxe mais limpa e uma comunidade gigante que ajuda iniciantes. Java é mais verboso e exige mais configuração, o que pode frustrar no começo.\n\n## Por que Python vence para iniciantes?\n\n- **Sintaxe simples**: código Python parece quase inglês. `print(\"Olá\")` vs `System.out.println(\"Olá\");` — a diferença é imensa.\n- **Menos burocracia**: em Python você escreve e roda. Em Java precisa de classes, métodos `main`, compilação...\n- **Curva de aprendizado rápida**: foca em lógica de programação, não em detalhes da linguagem.\n- **Comunidade amigável**: abundância de tutoriais para iniciantes, especialmente em português.\n\n## Quando Java pode ser melhor?\n\nSó se você já tem um objetivo específico: trabalhar em grandes empresas (bancos, sistemas corporativos) ou desenvolver apps Android nativos. Mas mesmo assim, aprenda Python primeiro — os conceitos de programação são os mesmos, e depois migrar para Java é mais fácil.\n\n## Dica prática\n\nComece com Python. Faça alguns projetinhos (calculadora, jogo da velha, web scraper simples). Quando sentir confiança, aí sim considere Java se precisar.\n\n**Conclusão**: Python é a escolha certa para 90% dos iniciantes. Mais rápido, mais divertido, mais produtivo. Java pode esperar.\n\nQuer dar o primeiro passo? Veja nosso [guia completo de Python para iniciantes no MeuPasso](https://meupasso.com/python-iniciantes).\n"
  },
  {
    "imagem": "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80",
    "titulo": "Quanto Tempo Leva para Aprender Programação do Zero?",
    "slug": "quanto-tempo-aprender-programacao",
    "descricao": "Sem enrolação: quanto tempo leva para aprender programação e conseguir o primeiro emprego.",
    "data": "2026-06-06",
    "tags": [
      "carreira",
      "iniciantes"
    ],
    "content": "\nDá para conseguir o primeiro emprego em programação entre 6 meses e 1 ano e meio, estudando de forma consistente (3 a 6 horas por dia). O tempo exato depende de quanto tempo você pode dedicar, da sua base em lógica e da área escolhida. Se for full-time e focado, 6 meses é realista. Se for estudando nas horas vagas, prepare-se para 12 a 18 meses.\n\n## O que define o prazo realista\n\nO maior fator é a **consistência**. Estudar 2 horas todo dia rende mais que 10 horas no fim de semana. Outro ponto: foco em uma stack específica. Não tente aprender tudo. Escolha uma área (web, mobile, dados) e domine o básico dela — HTML, CSS, JavaScript para front-end, por exemplo. Projetos práticos contam mais que teoria.\n\n## Como chegar lá mais rápido\n\nMonte um portfólio com 3 a 5 projetos reais (clonar sites, criar um app simples). Pratique lógica de programação com sites como LeetCode ou HackerRank. Participe de comunidades (Discord, grupos de WhatsApp) para network. E, principalmente, aplique para vagas júnior mesmo sem se sentir 100% pronto — o mercado valoriza quem mostra iniciativa.\n\n## Conclusão\n\nNão existe mágica: programação exige prática diária, mas o primeiro emprego chega mais rápido do que você imagina se você focar no que realmente importa. Quer um plano passo a passo? Veja o guia completo no [MeuPasso](https://meupasso.com.br/aprender-programar-primeiro-emprego).\n"
  }
];
